from datetime import datetime
from fastapi import APIRouter, HTTPException, Depends, status
from pydantic import BaseModel
from typing import Optional
from sqlalchemy.orm import Session

from config import get_openai_api_key, set_openai_api_key_override
from services.auth_service.api import get_current_user, get_current_user_optional
from services.auth_service.models import User
from services.ai_orchestrator_service.services import AIOrchestrator
from database import get_db
from langchain_bot import ArabiaLangChainBot
from models import Conversation, Message, Tenant
from services.customer_bot_flow import (
    append_handoff_agent_line,
    format_kb_reply,
    lookup_agent_display_name,
    process_customer_bot_message,
    public_templates_payload,
    resolve_bot_template,
)
from services.customer_bot_flow.session_reset import release_agent_and_clear_bot_flow
from services.human_handoff_intent import is_slash_reset_command
from services.agent_portal_service.broadcast import notify_bot_handoff_assigned
from services.agent_routing_service.api import assign_from_bot_flow

router = APIRouter()


class ChatMessage(BaseModel):
    tenant_id: int = 1
    conversation_id: Optional[int] = None
    message: str
    channel: str  # whatsapp, web, portal
    phone: Optional[str] = None
    store_code: Optional[str] = None
    customer_id: Optional[int] = None
    store_id: Optional[int] = None
    language: Optional[str] = None


class LanguageDetectRequest(BaseModel):
    message: str


@router.get("/customer-bot-templates")
async def get_customer_bot_templates():
    """
    Exact strings for structured onboarding (entry, menus, verify, etc.).
    These are returned as-is by the bot flow engine — not generated by the LLM.
    """
    return public_templates_payload()


@router.post("/chat")
async def process_chat_message(message: ChatMessage, db: Session = Depends(get_db)):
    """
    Process incoming chat with structured onboarding flow when a conversation exists,
    then LangChain for knowledge/AI segments; otherwise legacy AI with store context.
    """
    orchestrator = AIOrchestrator()
    bot = ArabiaLangChainBot(db=db)

    conversation: Conversation | None = None
    if message.conversation_id is not None:
        conversation = (
            db.query(Conversation)
            .filter(Conversation.id == message.conversation_id)
            .first()
        )

    if conversation and conversation.agent_id:
        detected_language = message.language or await orchestrator.detect_language(
            message.message
        )
        if is_slash_reset_command(message.message):
            release_agent_and_clear_bot_flow(conversation)
            db.add(conversation)
            db.commit()
            db.refresh(conversation)
        else:
            reply_ack = resolve_bot_template(detected_language, "agent_relay_ack")
            db.add(
                Message(
                    conversation_id=conversation.id,
                    content=message.message,
                    sender_type="customer",
                    sender_id=None,
                    language=detected_language,
                    created_at=datetime.utcnow(),
                )
            )
            db.add(
                Message(
                    conversation_id=conversation.id,
                    content=reply_ack,
                    sender_type="ai",
                    sender_id=None,
                    language=detected_language,
                    created_at=datetime.utcnow(),
                )
            )
            conversation.updated_at = datetime.utcnow()
            db.add(conversation)
            db.commit()
            return {
                "reply_text": reply_ack,
                "language": detected_language,
                "escalate": False,
                "human_agent_active": True,
                "context": {"customer": {}, "recent_orders": []},
            }

    flow = await process_customer_bot_message(
        db=db,
        conversation=conversation,
        user_message=message.message,
        tenant_id=message.tenant_id,
        orchestrator=orchestrator,
        phone=message.phone,
    )

    if conversation and flow.merge_metadata:
        conversation.conversation_metadata = flow.merge_metadata

    detected_language = message.language or await orchestrator.detect_language(message.message)
    bf_lang = (flow.merge_metadata.get("bot_flow") or {}).get("lang")
    if isinstance(bf_lang, str) and bf_lang.strip():
        detected_language = bf_lang

    if not flow.handled:
        flow_state = flow.merge_metadata.get("bot_flow") if isinstance(flow.merge_metadata, dict) else None
        customer_context = await orchestrator.fetch_customer_context(
            phone=message.phone,
            message_text=message.message,
            bot_flow=flow_state,
        )
        recent_orders = customer_context.get("recent_orders") or []
        customer = customer_context.get("customer") or {}
        reply_text = await bot.generate_reply(
            tenant_id=message.tenant_id,
            user_message=message.message,
            channel=message.channel,
            language=detected_language,
            customer_context=customer,
            recent_orders=recent_orders,
            fetch_context=customer_context,
            bot_flow=flow_state,
            conversation_id=conversation.id if conversation else None,
        )
        if message.conversation_id is not None and conversation:
            db.add(
                Message(
                    conversation_id=conversation.id,
                    content=message.message,
                    sender_type="customer",
                    sender_id=None,
                    language=detected_language,
                    created_at=datetime.utcnow(),
                )
            )
            db.add(
                Message(
                    conversation_id=conversation.id,
                    content=reply_text,
                    sender_type="ai",
                    sender_id=None,
                    language=detected_language,
                    created_at=datetime.utcnow(),
                )
            )
            conversation.updated_at = datetime.utcnow()
            db.add(conversation)
            db.commit()
        escalate = await orchestrator.should_escalate(message.message)
        return {
            "reply_text": reply_text,
            "language": detected_language,
            "escalate": escalate,
            "context": {"customer": customer, "recent_orders": recent_orders},
        }

    if flow.use_ai:
        if flow.skip_store_api:
            customer: dict = {}
            recent_orders: list = []
        else:
            flow_state = flow.merge_metadata.get("bot_flow") if isinstance(flow.merge_metadata, dict) else None
            customer_context = await orchestrator.fetch_customer_context(
                phone=message.phone,
                message_text=message.message,
                bot_flow=flow_state,
            )
            recent_orders = customer_context.get("recent_orders") or []
            customer = customer_context.get("customer") or {}
        reply_text = await bot.generate_reply(
            tenant_id=message.tenant_id,
            user_message=flow.ai_user_message,
            channel=message.channel,
            language=detected_language,
            customer_context=customer,
            recent_orders=recent_orders,
            fetch_context=customer_context if not flow.skip_store_api else None,
            bot_flow=flow_state if not flow.skip_store_api else (
                flow.merge_metadata.get("bot_flow") if isinstance(flow.merge_metadata, dict) else None
            ),
            conversation_id=conversation.id if conversation else None,
        )
        if flow.skip_store_api:
            reply_text = format_kb_reply(bf_lang or detected_language, reply_text)
    else:
        reply_text = flow.reply_text
        bf = flow.merge_metadata.get("bot_flow") or {}
        if bf.get("customer_kind") == "new" or not bf.get("verified"):
            customer, recent_orders = {}, []
        else:
            flow_state = flow.merge_metadata.get("bot_flow") if isinstance(flow.merge_metadata, dict) else None
            customer_context = await orchestrator.fetch_customer_context(
                phone=message.phone,
                message_text=message.message,
                bot_flow=flow_state,
            )
            recent_orders = customer_context.get("recent_orders") or []
            customer = customer_context.get("customer") or {}

    if conversation and flow.assign_team:
        bf = flow.merge_metadata.get("bot_flow") or {}
        kind = bf.get("customer_kind")
        assign_result = assign_from_bot_flow(
            db,
            tenant_id=message.tenant_id,
            conversation_id=conversation.id,
            store_id=conversation.store_id,
            customer_id=conversation.customer_id,
            routed_team=flow.assign_team,
            is_existing_customer=(kind == "existing" or bool(bf.get("verified"))),
        )
        db.refresh(conversation)
        if assign_result.agent_id is not None and assign_result.reason != "conversation_already_assigned":
            aname = lookup_agent_display_name(db, assign_result.agent_id)
            if aname:
                lang = (
                    bf_lang
                    if isinstance(bf_lang, str) and bf_lang.strip()
                    else detected_language
                )
                reply_text = append_handoff_agent_line(lang, reply_text, aname)
            await notify_bot_handoff_assigned(
                db,
                message.tenant_id,
                assign_result.agent_id,
                conversation.id,
                conversation.customer_id,
                conversation.store_id,
            )
        elif assign_result.agent_id is None and assign_result.reason == "no_available_agent":
            lang = (
                bf_lang
                if isinstance(bf_lang, str) and bf_lang.strip()
                else detected_language
            )
            extra = resolve_bot_template(lang, "handoff_unavailable")
            if extra:
                reply_text = f"{(reply_text or '').strip()}\n\n{extra}".strip()

    if conversation:
        db.add(
            Message(
                conversation_id=conversation.id,
                content=message.message,
                sender_type="customer",
                sender_id=None,
                language=detected_language,
                created_at=datetime.utcnow(),
            )
        )
        db.add(
            Message(
                conversation_id=conversation.id,
                content=reply_text,
                sender_type="ai",
                sender_id=None,
                language=detected_language,
                created_at=datetime.utcnow(),
            )
        )
        conversation.updated_at = datetime.utcnow()
        db.add(conversation)
        db.commit()

    escalate = flow.escalate or await orchestrator.should_escalate(message.message)
    return {
        "reply_text": reply_text,
        "language": detected_language,
        "escalate": escalate,
        "context": {"customer": customer, "recent_orders": recent_orders},
    }


@router.post("/verify-customer")
async def verify_customer():
    """Verify customer using store code, mobile, or email"""
    return {"message": "Customer verification endpoint"}


@router.post("/detect-language")
async def detect_language(payload: LanguageDetectRequest):
    """Detect message language: arabic | english | roman_urdu."""
    orchestrator = AIOrchestrator()
    language = await orchestrator.detect_language(payload.message)
    return {"language": language}


@router.post("/escalate")
async def escalate_to_agent():
    """Escalate conversation to human agent"""
    return {"message": "Agent escalation endpoint"}


# --- OpenAI API key config (admin Settings) ---

class OpenAIConfigUpdate(BaseModel):
    api_key: str


def _mask_openai_api_key(key: str) -> str:
    k = (key or "").strip()
    if not k:
        return ""
    if len(k) <= 8:
        return "••••••••"
    return f"{k[:3]}…{k[-4:]}"


@router.get("/openai-config")
async def get_openai_config(
    current_user: Optional[User] = Depends(get_current_user_optional),
):
    """
    Whether a key is configured. Admins (Bearer) also get a short masked preview (never the full key).
    """
    key = get_openai_api_key()
    configured = bool(key and key.strip())
    out: dict = {"key_configured": configured}
    if (
        current_user is not None
        and (current_user.role or "").lower() == "admin"
        and configured
    ):
        out["key_preview"] = _mask_openai_api_key(key or "")
    return out


@router.post("/openai-config")
async def update_openai_config(
    body: OpenAIConfigUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Admin only: set OpenAI API key for this tenant; persisted and applied to the bot immediately."""
    if (current_user.role or "").lower() != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only admin can update the OpenAI API key",
        )
    key = (body.api_key or "").strip()
    tenant = db.query(Tenant).filter(Tenant.id == current_user.tenant_id).first()
    if tenant is None:
        raise HTTPException(status_code=404, detail="Tenant not found")
    tenant.openai_api_key = key if key else None
    db.add(tenant)
    db.commit()

    set_openai_api_key_override(key if key else None)
    out: dict = {"key_configured": bool(key)}
    if key:
        out["key_preview"] = _mask_openai_api_key(key)
    return out
